const debrisData = [
  {
    name: "COSMOS 2251 DEB",
    color: 0xff0000,
    origin: "Va chạm giữa vệ tinh Cosmos 2251 và Iridium 33 (2009).",
    speed: "7.4 km/s",
    orbit: "LEO (~790 km)",
    impact:
      "Tạo >2000 mảnh rác. Gây nguy cơ va chạm dây chuyền (hiệu ứng Kessler).",
    research: "ESA/NASA mô phỏng quỹ đạo và xác suất va chạm.",
    action:
      "Thử nghiệm laser mặt đất và vệ tinh dọn rác (ClearSpace, Astroscale).",
    model: "./models/orbital_camera_v2.glb",
    mass: 8,
  },
  {
    name: "IRIDIUM 33 DEB",
    color: 0x3399ff,
    origin: "Mảnh vỡ từ vụ va chạm với Cosmos 2251 (2009).",
    speed: "7.5 km/s",
    orbit: "LEO (~780 km)",
    impact: "Hàng nghìn mảnh rác nhỏ, ảnh hưởng giao thông vệ tinh thương mại.",
    research: "NORAD theo dõi bằng radar không gian đa tầng.",
    action: "Tăng cường quy trình tránh va chạm chủ động bằng AI.",
    model: "./models/orbital_camera_v2.glb",
    mass: 9,
  },
  {
    name: "FENGYUN 1C DEB",
    color: 0x0000ff,
    origin: "Rác từ vụ thử vũ khí chống vệ tinh của Trung Quốc (2007).",
    speed: "7.8 km/s",
    orbit: "Polar Orbit (~865 km)",
    impact:
      "Tạo ~3000 mảnh rác. Là sự kiện gây ô nhiễm quỹ đạo nghiêm trọng nhất.",
    research: "NASA/ESA theo dõi bằng radar Space Fence.",
    action: "Cấm thử nghiệm ASAT, ClearSpace-1 thu hồi rác lớn.",
    model: "./models/orbital_camera_v2.glb",
    mass: 11,
  },
  {
    name: "ARIANE 5 R/B",
    color: 0xffff00,
    origin: "Tầng tên lửa Ariane 5 còn lại sau phóng vệ tinh châu Âu.",
    speed: "7.2 km/s",
    orbit: "GTO / LEO",
    impact: "Có thể nổ do nhiên liệu dư, tạo mảnh vụn thứ cấp.",
    research: "ESA thử nghiệm robot thu hồi tầng tên lửa.",
    action: "ClearSpace-1 (2026) – sứ mệnh thu gom rác đầu tiên.",
    model: "./models/orbital_camera_v2.glb",
    mass: 8,
  },
  {
    name: "DELTA 2 R/B",
    color: 0x0099ff,
    origin: "Tầng đẩy Delta 2 của NASA (thập niên 1990).",
    speed: "7.4 km/s",
    orbit: "LEO (~850 km)",
    impact: "Một số tầng phát nổ, tạo hàng trăm mảnh nhỏ.",
    research: "NASA thiết lập quy trình xả nhiên liệu bắt buộc.",
    action: "Áp dụng quy định 'passivation' để vô hiệu năng lượng dư.",
    model: "./models/orbital_camera_v2.glb",
    mass: 4,
  },
  {
    name: "SL-16 R/B",
    color: 0xff00ff,
    origin: "Tầng đẩy tên lửa SL-16 (Nga).",
    speed: "7.6 km/s",
    orbit: "LEO (~850 km)",
    impact: "Hơn 50 tầng SL-16 vẫn trôi tự do, từng phát nổ nhiều lần.",
    research: "ESA & Roscosmos hợp tác phát triển van xả tự động.",
    action: "Hạ quỹ đạo có kiểm soát và thu hồi bằng lưới.",
    model: "./models/orbital_camera_v2.glb",
    mass: 12,
  },
  {
    name: "VANGUARD 1",
    color: 0x00cc99,
    origin: "Vệ tinh đầu tiên của Mỹ (1958) – hiện đã ngừng hoạt động.",
    speed: "7.8 km/s",
    orbit: "MEO (~650 km)",
    impact: "Là vật thể nhân tạo lâu đời nhất còn tồn tại trên quỹ đạo.",
    research: "Dùng để nghiên cứu lực kéo khí quyển.",
    action: "Được giữ làm di sản không gian, không can thiệp.",
    model: "./models/orbital_camera_v2.glb",
    mass: 20,
  },
  {
    name: "COSMOS 1300 DEB",
    color: 0x993333,
    origin: "Mảnh vỡ từ vệ tinh do thám Liên Xô (1970s).",
    speed: "7.6 km/s",
    orbit: "LEO (~800 km)",
    impact: "Khó theo dõi, tăng rủi ro hiệu ứng Kessler.",
    research: "ESA dùng radar Space Fence để phát hiện rác nhỏ.",
    action: "Sử dụng lưới điện từ hoặc robot thu hồi quỹ đạo thấp.",
    model: "./models/orbital_camera_v2.glb",
    mass: 50,
  },
  {
    name: "ENVISAT",
    color: 0x33ffcc,
    origin: "Vệ tinh quan sát Trái Đất của ESA, mất liên lạc năm 2012.",
    speed: "7.5 km/s",
    orbit: "LEO (~790 km)",
    impact: "Là một trong các vật thể lớn nhất còn trôi tự do (~8 tấn).",
    research: "ESA giám sát liên tục và mô phỏng va chạm tiềm ẩn.",
    action: "Mục tiêu thu hồi trong dự án ClearSpace-2.",
    model: "./models/orbital_camera_v2.glb",
    mass: 6,
  },
  {
    name: "NOAA 16 DEB",
    color: 0xcc66ff,
    origin: "Vệ tinh khí tượng của Mỹ, vỡ năm 2015 do nổ pin.",
    speed: "7.4 km/s",
    orbit: "LEO (~870 km)",
    impact: "Tạo hơn 200 mảnh nhỏ.",
    research: "Phân tích nguyên nhân vỡ từ áp suất pin nhiệt.",
    action: "NASA ban hành tiêu chuẩn an toàn pin sau nhiệm vụ.",
    model: "./models/orbital_camera_v2.glb",
    mass: 9,
  },
  {
    name: "COSMOS 1408 DEB",
    color: 0xff6600,
    origin: "Rác từ vụ thử ASAT của Nga (2021).",
    speed: "7.6 km/s",
    orbit: "LEO (~480 km)",
    impact: "Tạo 1500 mảnh, đe dọa ISS và vệ tinh Starlink.",
    research: "Theo dõi quỹ đạo mảnh bằng Space-Track.",
    action: "Liên Hiệp Quốc yêu cầu cấm thử ASAT phá hoại.",
    model: "./models/orbital_camera_v2.glb",
    mass: 11,
  },
  {
    name: "ATLAS CENTAUR R/B",
    color: 0x99ff00,
    origin: "Tầng tên lửa Mỹ phóng thập niên 1960s, còn lại trên quỹ đạo cao.",
    speed: "3.1 km/s",
    orbit: "HEO (~36000 km)",
    impact: "Có nguy cơ rơi tự do không kiểm soát.",
    research: "Theo dõi bằng kính viễn vọng mặt đất.",
    action: "Dự án ADRAS-J (Nhật Bản) thử tiếp cận thu hồi.",
    model: "./models/orbital_camera_v2.glb",
    mass: 8,
  },
  {
    name: "COSMOS 482 DESCENT MODULE",
    color: 0x9966ff,
    origin: "Tàu vũ trụ Liên Xô bị lỗi phóng năm 1972.",
    speed: "7.3 km/s",
    orbit: "LEO (~2200 km)",
    impact: "Khối nặng 500 kg, có khả năng rơi xuống Trái Đất.",
    research: "Các nhà thiên văn theo dõi chu kỳ phân rã khí quyển.",
    action: "Theo dõi và chuẩn bị biện pháp hạ an toàn.",
    model: "./models/orbital_camera_v2.glb",
    mass: 8,
  },
  {
    name: "TIANGONG-1",
    color: 0xffcc00,
    origin: "Trạm vũ trụ Trung Quốc bị mất kiểm soát (2018).",
    speed: "7.7 km/s",
    orbit: "LEO (~330 km)",
    impact: "Rơi xuống Thái Bình Dương năm 2018.",
    research: "Mô hình hóa phân rã khí quyển và rơi tự do.",
    action: "Thiết lập quy định hạ quỹ đạo có kiểm soát bắt buộc.",
    model: "./models/orbital_camera_v2.glb",
    mass: 9,
  },
  {
    name: "PEGASUS R/B",
    color: 0x00ff66,
    origin: "Tầng đẩy từ hệ thống tên lửa Pegasus, Mỹ.",
    speed: "7.4 km/s",
    orbit: "LEO (~700 km)",
    impact: "Một số tầng mất kiểm soát, gây va chạm tiềm ẩn.",
    research: "DARPA đánh giá khả năng tái sử dụng tầng đẩy.",
    action: "Tăng thiết kế tự hủy có kiểm soát sau tách tầng.",
    model: "./models/orbital_camera_v2.glb",
    mass: 12,
  },
  {
    name: "H-2A R/B",
    color: 0x3366cc,
    origin: "Tầng đẩy của Nhật Bản, còn lại sau phóng vệ tinh MTSAT.",
    speed: "7.3 km/s",
    orbit: "LEO (~500 km)",
    impact: "Gây nguy cơ nhỏ với các vệ tinh hoạt động thấp quỹ đạo.",
    research: "JAXA giám sát qua hệ thống radar quốc gia.",
    action: "Thử nghiệm công nghệ dây điện từ (EDR) để hạ dần quỹ đạo.",
    model: "./models/orbital_camera_v2.glb",
    mass: 8,
  },
];

export default debrisData;
